import type { Product, Category } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Espresso Shot",
    description: "Rich and intense coffee shot, perfect for a quick energy boost.",
    price: 99,
    background_image: '/images/bgimage-products.png',
    foreground_image: '/images/coffee-11.png',
    category: "coffee",
    featured: true,
    rating: 4.5,
    in_stock: true,
    reviews: 145,
    milk_percentage: 70,
    coffee_percentage: 30,
  },
  {
    id: "2",
    name: "Cappuccino",
    description: "Classic Italian coffee with equal parts espresso, steamed milk, and foam.",
    price: 149,
    background_image: '/images/bgimage-products.png',
    foreground_image: '/images/coffee-19.png',
    category: "coffee",
    featured: true,
    rating: 5,
    in_stock: false,
    reviews: 183,
    milk_percentage: 80,
    coffee_percentage: 20,
  },
  {
    id: "3",
    name: "Latte",
    description: "Smooth and creamy coffee with espresso and steamed milk.",
    price: 99,
    background_image: '/images/bgimage-products.png',
    foreground_image: '/images/coffee-14.png',
    category: "coffee",
    featured: true,
    rating: 4.5,
    in_stock: true,
    reviews: 120,
    milk_percentage: 40,
    coffee_percentage: 60,
  },
  {
    id: "4",
    name: "Mocha",
    description: "Delicious blend of espresso, chocolate, and steamed milk.",
    price: 199,
    background_image: '/images/bgimage-products.png',
    foreground_image: '/images/coffee-15.png',
    category: "coffee",
    featured: true,
    rating: 3.5,
    in_stock: true,
    reviews: 150,
    milk_percentage: 80,
    coffee_percentage: 20,
  },
  {
    id: "5",
    name: "Americano",
    description: "Espresso diluted with hot water, similar strength to regular coffee.",
    price: 129,
    background_image: '/images/bgimage-products.png',
    foreground_image: '/images/coffee-17.png',
    category: "coffee",
    rating: 4.5,
    in_stock: false,
    reviews: 110,
    milk_percentage: 80,
    coffee_percentage: 20,
  },
  {
    id: "6",
    name: "Macchiato",
    description: "Espresso with a small amount of foamed milk.",
    price: 119,
    background_image: '/images/bgimage-products.png',
    foreground_image: '/images/coffee-18.png',
    category: "coffee",
    rating: 1.5,
    in_stock: true,
    reviews: 120,
    milk_percentage: 90,
    coffee_percentage: 10,
  },
  {
    id: "7",
    name: "Croissant",
    description: "Espresso with steamed milk and minimal foam.",
    price: 99,
    background_image: '/images/bgimage-products.png',
    foreground_image: '/images/coffee-20.png',
    category: "coffee",
    rating: 2.5,
    in_stock: false,
    reviews: 250,
    milk_percentage: 50,
    coffee_percentage: 50,
  },
  {
    id: "8",
    name: "Coffee with Whipped Cream",
    description: "Coffee brewed with cold water over a long period, resulting in a smooth taste.",
    price: 179,
    background_image: '/images/bgimage-products.png',
    foreground_image: '/images/coffee-21.png',
    category: "honey",
    featured: true,
    rating: 5,
    in_stock: true,
    reviews: 150,
    milk_percentage: 50,
    coffee_percentage: 50,
  },
  {
    id: "9",
    name: "Foamy Macchiato",
    description: "Buttery, flaky pastry, perfect with coffee.",
    price: 99,
    background_image: '/images/bgimage-products.png',
    foreground_image: '/images/coffee-23.png',
    category: "food",
    rating: 4.5,
    in_stock: false,
    reviews: 150,
    milk_percentage: 50,
    coffee_percentage: 50,
  },
  {
    id: "10",
    name: "Black Coffee",
    description: "Rich chocolate muffin with chocolate chips.",
    price: 199,
    background_image: '/images/bgimage-products.png',
    foreground_image: '/images/coffee-24.png',
    category: "food",
    rating: 2.5,
    in_stock: true,
    reviews: 150,
    milk_percentage: 50,
    coffee_percentage: 50,
  },
  {
    id: "11",
    name: "Dark Chocolate",
    description: "Tender scone filled with juicy blueberries.",
    price: 149,
    background_image: '/images/bgimage-products.png',
    foreground_image: '/images/coffee-25.png',
    category: "beans",
    rating: 3.5,
    in_stock: false,
    reviews: 150,
    milk_percentage: 50,
    coffee_percentage: 50,
  },
  {
    id: "12",
    name: "Hot Chocolate",
    description: "Premium dark roast coffee beans, 12oz bag.",
    price: 159,
    background_image: '/images/bgimage-products.png',
    foreground_image: '/images/coffee-26.png',
    category: "beans",
    featured: true,
    rating: 5,
    in_stock: true,
    reviews: 150,
    milk_percentage: 50,
    coffee_percentage: 50,
  },
]

export const categories: Category[] = [
  {
    id: "coffee",
    name: "Coffee",
    description: "Our signature coffee drinks",
    image: "/images/bgimage-products.png",
  },
  {
    id: "tea",
    name: "Tea",
    description: "Premium loose leaf teas",
    image: "/images/bgimage-products.png",
  },
  {
    id: "food",
    name: "Food",
    description: "Pastries and snacks",
    image: "/images/bgimage-products.png",
  },
  {
    id: "beans",
    name: "Coffee Beans",
    description: "Take our coffee home",
    image: "/images/bgimage-products.png",
  },
  {
    id: "equipment",
    name: "Equipment",
    description: "Coffee brewing equipment",
    image: "/images/bgimage-products.png",
  },
]

